### ISSUE TITLE
Can't connect using IE6

### ISSUE THREAD

**Issue by rdebath** [jmhodges/howsmyssl#173]
The website will not accept connections from IE6 on XP or IE6 on Windows 2000.

This happens even though `SSLv3` and  `TLS_RSA_WITH_3DES_EDE_CBC_SHA` (`DES-CBC3-SHA`) are both supported by IE6 and the website does respond to OpenSSL s_client configured to use only these items. The browser does also have TLSv1.0, however, even if this is the only protocol enabled it does not work. The browser does accept RSA certificates of 2048 bits as the https://www.mozilla.org site works and has a certificate of this size.

I think the problem is that the LE certificate you're using has `SHA2` as it's message digest algorithm and this is not supported by IE6.

One possible solution (it may be the one used by Mozilla) is to supply a different certificate if the client doesn't support SNI. (Possibly even a self-signed certificate)

**Comment by jmhodges** [comment]
Ah, IE6 is not supported. IE6 was no longer supported by Microsoft itself as of 2014, and I'm gonna take their lead. (Other newer versions have support SHA256 for a decade or two.) 

If you do need a custom installation of howsmyssl because IE6 is required, there are build instructions in the README, though!

Have a nice day!

**Comment by rdebath** [comment]
Awww, that's a shame :grin:
