### ISSUE TITLE
Session Ticket Support

### ISSUE THREAD

**Issue by JohnPlanetary** [jmhodges/howsmyssl#327]
In: https://www.howsmyssl.com/s/about.html#session-ticket-support

It appears that Session Ticket Support has its own problems already mention, you may want to have a look also at: https://www.privateinternetaccess.com/blog/supercookey-a-supercookie-built-into-tls-1-2-and-1-3/

These is also a one more way to make it easy to track devices.

Probably better not to be enabled?

**Comment by jmhodges** [comment]
So, that work is true of any TLS session resumption (like session caching), not just tickets. TLS session resumption is useful and the privacy problems have mitigations available to them. There may be a day I don't recommend them, but it'll be because I'm convinced by folks that the infra of session caching on the server-side is easier to do securely than session tickets (I've waffled for years after I first added scaled-out session tickets to a well-known social media site).
