### ISSUE TITLE
Support for client certificates in API

### ISSUE THREAD

**Issue by yschimke** [jmhodges/howsmyssl#69]
Feature Request:

There seemingly isn't any good test server for SSL with client certificates.  Support in howsmyssl for client certificates would be useful when testing with smartcards etc.  

This is possible with openssl s_server -verify or -Verify.

It seems like the go tls supports it, but it just isn't possible for the server to request or shown anywhere in the output.

**Comment by jmhodges** [comment]
Sorry, this is a little out of scope for howsmyssl because it requires something other than the default settings of the client.

Go's crypto/tls does have this data on [ConnectionState](https://golang.org/pkg/crypto/tls/#ConnectionState) as "PeerCertificates". Looks like you could use that locally to do the work if you need it.
