### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by senthiltls** [jmhodges/howsmyssl#95]
Hi ,

we are using  "https://www.howsmyssl.com/a/check?callback=parseTLSinfo" in javascript.
to get  the TLS version to verify the user using correct browser or not in  our website.but i  am getting
this error "429- Too Many Requests" .may i know how do i fix it?

Thanks & Regards
Senthilnathan

**Comment by jmhodges** [comment]
Some code that will soon be turned on permanently was put out prematurely. Fixed in https://github.com/jmhodges/howsmyssl/pull/96

Be advised that using the howsmyssl API from your user's browsers is not guaranteed. You'll want to email jeff@darkishgreen.com for pricing information to ensure that you can continue to use the API.

**Comment by jmhodges** [comment]
The fix is now deployed. Thanks for your report!
